// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_stan_fit4HDIc_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4HDIcCauchy_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4HDIcUnif_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4HDId_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4HDIdCauchy_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4HDIdCauchyFixed_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4HDIdFixed_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4HDIdUnif_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4HDIdUnifFixed_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4HDIstandard_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4HDIstandardFixed_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4HDIstandardHetero_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4HDIc_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4HDIc_mod, 0},
    {"_rcpp_module_boot_stan_fit4HDIcCauchy_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4HDIcCauchy_mod, 0},
    {"_rcpp_module_boot_stan_fit4HDIcUnif_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4HDIcUnif_mod, 0},
    {"_rcpp_module_boot_stan_fit4HDId_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4HDId_mod, 0},
    {"_rcpp_module_boot_stan_fit4HDIdCauchy_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4HDIdCauchy_mod, 0},
    {"_rcpp_module_boot_stan_fit4HDIdCauchyFixed_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4HDIdCauchyFixed_mod, 0},
    {"_rcpp_module_boot_stan_fit4HDIdFixed_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4HDIdFixed_mod, 0},
    {"_rcpp_module_boot_stan_fit4HDIdUnif_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4HDIdUnif_mod, 0},
    {"_rcpp_module_boot_stan_fit4HDIdUnifFixed_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4HDIdUnifFixed_mod, 0},
    {"_rcpp_module_boot_stan_fit4HDIstandard_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4HDIstandard_mod, 0},
    {"_rcpp_module_boot_stan_fit4HDIstandardFixed_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4HDIstandardFixed_mod, 0},
    {"_rcpp_module_boot_stan_fit4HDIstandardHetero_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4HDIstandardHetero_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_rmBayes(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
